// Electromagnetic spectrum data
// Frequencies in Hz

// High-level EM spectrum categories that group the ITU bands into the
// familiar physics labels (radio, microwaves, IR, visible, UV, X-ray, gamma).
// Boundaries are non-overlapping and align with the SPECTRUM_BANDS edges.
export const SPECTRUM_CATEGORIES = [
  { name: "Radio",       freqMin: 3,       freqMax: 3e9 },
  { name: "Microwaves",  freqMin: 3e9,     freqMax: 300e9 },
  { name: "Infrared",    freqMin: 300e9,   freqMax: 430e12 },
  { name: "Visible",     freqMin: 430e12,  freqMax: 750e12 },
  { name: "Ultraviolet", freqMin: 750e12,  freqMax: 30e15 },
  { name: "X-rays",      freqMin: 30e15,   freqMax: 30e18 },
  { name: "Gamma",       freqMin: 30e18,   freqMax: 3e22 },
];

export const SPECTRUM_BANDS = [
  {
    name: "Extremely Low Frequency",
    abbr: "ELF",
    freqMin: 3,
    freqMax: 30,
    unit: "Hz",
    color: "#4a0080",
    wavelengthMin: "10,000 km",
    wavelengthMax: "100,000 km",
  },
  {
    name: "Super Low Frequency",
    abbr: "SLF",
    freqMin: 30,
    freqMax: 300,
    unit: "Hz",
    color: "#5a0090",
    wavelengthMin: "1,000 km",
    wavelengthMax: "10,000 km",
  },
  {
    name: "Ultra Low Frequency",
    abbr: "ULF",
    freqMin: 300,
    freqMax: 3000,
    unit: "Hz",
    color: "#6a00a0",
    wavelengthMin: "100 km",
    wavelengthMax: "1,000 km",
  },
  {
    name: "Very Low Frequency",
    abbr: "VLF",
    freqMin: 3e3,
    freqMax: 30e3,
    unit: "kHz",
    color: "#0000cc",
    wavelengthMin: "10 km",
    wavelengthMax: "100 km",
  },
  {
    name: "Low Frequency",
    abbr: "LF",
    freqMin: 30e3,
    freqMax: 300e3,
    unit: "kHz",
    color: "#0055cc",
    wavelengthMin: "1 km",
    wavelengthMax: "10 km",
  },
  {
    name: "Medium Frequency",
    abbr: "MF",
    freqMin: 300e3,
    freqMax: 3e6,
    unit: "MHz",
    color: "#0088cc",
    wavelengthMin: "100 m",
    wavelengthMax: "1 km",
  },
  {
    name: "High Frequency",
    abbr: "HF",
    freqMin: 3e6,
    freqMax: 30e6,
    unit: "MHz",
    color: "#00aacc",
    wavelengthMin: "10 m",
    wavelengthMax: "100 m",
  },
  {
    name: "Very High Frequency",
    abbr: "VHF",
    freqMin: 30e6,
    freqMax: 300e6,
    unit: "MHz",
    color: "#00cc88",
    wavelengthMin: "1 m",
    wavelengthMax: "10 m",
  },
  {
    name: "Ultra High Frequency",
    abbr: "UHF",
    freqMin: 300e6,
    freqMax: 3e9,
    unit: "GHz",
    color: "#44cc44",
    wavelengthMin: "10 cm",
    wavelengthMax: "1 m",
  },
  {
    name: "Super High Frequency",
    abbr: "SHF",
    freqMin: 3e9,
    freqMax: 30e9,
    unit: "GHz",
    color: "#aacc00",
    wavelengthMin: "1 cm",
    wavelengthMax: "10 cm",
  },
  {
    name: "Extremely High Frequency",
    abbr: "EHF",
    freqMin: 30e9,
    freqMax: 300e9,
    unit: "GHz",
    color: "#cc8800",
    wavelengthMin: "1 mm",
    wavelengthMax: "10 mm",
  },
  {
    name: "Infrared",
    abbr: "IR",
    freqMin: 300e9,
    freqMax: 430e12,
    unit: "THz",
    color: "#cc4400",
    wavelengthMin: "700 nm",
    wavelengthMax: "1 mm",
  },
  {
    name: "Visible Light",
    abbr: "VIS",
    freqMin: 430e12,
    freqMax: 750e12,
    unit: "THz",
    color: "rainbow",
    wavelengthMin: "400 nm",
    wavelengthMax: "700 nm",
  },
  {
    name: "Ultraviolet",
    abbr: "UV",
    freqMin: 750e12,
    freqMax: 30e15,
    unit: "PHz",
    color: "#8800cc",
    wavelengthMin: "10 nm",
    wavelengthMax: "400 nm",
  },
  {
    name: "X-Ray",
    abbr: "X",
    freqMin: 30e15,
    freqMax: 30e18,
    unit: "EHz",
    color: "#aa00ff",
    wavelengthMin: "0.01 nm",
    wavelengthMax: "10 nm",
  },
  {
    name: "Gamma Ray",
    abbr: "γ",
    freqMin: 30e18,
    freqMax: 3e22,
    unit: "EHz",
    color: "#ff00ff",
    wavelengthMin: "< 0.01 nm",
    wavelengthMax: "0.01 nm",
  },
];

export const TECHNOLOGIES = [
  // AC Mains Power (ELF)
  {
    id: "ac-power",
    name: "AC Power",
    fullName: "Alternating Current (Mains Power)",
    frequency: 60,
    freqDisplay: "50 – 60 Hz",
    color: "#ffdd44",
    svgIcon: "acpower",
    description: "Household and industrial electrical power delivered as a slowly alternating current",
    examples: [
      "Home wall outlets (120 / 230 V)",
      "Overhead transmission lines",
      "Household appliances",
      "Industrial motors & lighting",
    ],
    band: "ELF",
    range: "Wired distribution grid",
    standard: "IEC 60038 (50 / 60 Hz)",
    powerW: 1000,
    powerDisplay: "~1 kW (household circuit)",
  },
  // Qi Wireless Charging (LF)
  {
    id: "qi-charging",
    name: "Qi Charging",
    fullName: "Qi Wireless Charging",
    frequency: 150e3,
    freqDisplay: "100 – 205 kHz",
    color: "#66ff88",
    svgIcon: "charging",
    description: "Inductive coupling that charges phones and wearables through a pad",
    examples: [
      "Wireless phone chargers (MagSafe base)",
      "Wireless earbud cases",
      "Electric toothbrushes",
      "Some smartwatches",
    ],
    band: "LF",
    range: "~4 cm",
    standard: "Qi (WPC) / Qi2",
    powerW: 15,
    powerDisplay: "5 – 15 W",
  },
  // NFC
  {
    id: "nfc",
    name: "NFC",
    fullName: "Near Field Communication",
    frequency: 13.56e6,
    freqDisplay: "13.56 MHz",
    color: "#00c8ff",
    svgIcon: "nfc",
    description: "Short-range wireless for contactless payments and data transfer",
    examples: [
      "Apple Pay / Google Pay",
      "Contactless credit cards",
      "Transit cards (Oyster, Metro)",
      "Keycard access systems",
    ],
    band: "HF",
    range: "~20 cm",
    standard: "ISO/IEC 14443",
    powerW: 0.2,
    powerDisplay: "~200 mW (reader)",
  },
  // AM Radio
  {
    id: "am-radio",
    name: "AM Radio",
    fullName: "Amplitude Modulation Radio",
    frequency: 1e6,
    freqDisplay: "535 kHz – 1.7 MHz",
    color: "#ff9900",
    svgIcon: "radio",
    description: "Analog broadcast radio using amplitude modulation",
    examples: [
      "News & talk radio stations",
      "Sports broadcasts",
      "Emergency broadcasts",
      "Religious programming",
    ],
    band: "MF",
    range: "Hundreds of miles",
    standard: "ITU Region assignments",
    powerW: 10000,
    powerDisplay: "250 W – 50 kW (broadcast)",
  },
  // CB Radio (HF)
  {
    id: "cb-radio",
    name: "CB Radio",
    fullName: "Citizens Band Radio",
    frequency: 27e6,
    freqDisplay: "26.965 – 27.405 MHz",
    color: "#ff8844",
    svgIcon: "radio",
    description: "Short-distance two-way voice radio open to the public without a license",
    examples: [
      "Long-haul trucker chatter",
      "Off-road & 4×4 groups",
      "Farm & ranch operations",
      "Hobbyist 'handles' community",
    ],
    band: "HF",
    range: "~5 – 15 km",
    standard: "FCC Part 95 Subpart D",
    powerW: 4,
    powerDisplay: "4 W (FCC max)",
  },
  // FM Radio
  {
    id: "fm-radio",
    name: "FM Radio",
    fullName: "Frequency Modulation Radio",
    frequency: 100e6,
    freqDisplay: "87.5 – 108 MHz",
    color: "#ff6600",
    svgIcon: "radio",
    description: "Analog broadcast radio using frequency modulation",
    examples: [
      "Music stations",
      "Public radio (NPR)",
      "Sports commentary",
      "Traffic & weather radio",
    ],
    band: "VHF",
    range: "~50 miles",
    standard: "ITU Band 8",
    powerW: 50000,
    powerDisplay: "3 – 100 kW ERP (broadcast)",
  },
  // Remote Control (IR)
  {
    id: "ir-remote",
    name: "IR Remote",
    fullName: "Infrared Remote Control",
    frequency: 38e3,
    freqDisplay: "300 GHz – 430 THz",
    color: "#cc2200",
    svgIcon: "remote",
    description: "Infrared light pulses used for line-of-sight remote control",
    examples: [
      "TV remote controls",
      "Set-top box remotes",
      "Air conditioner remotes",
      "DVD/Blu-ray players",
    ],
    band: "IR",
    range: "~10 meters",
    standard: "RC-5, NEC protocol",
    isIR: true,
    powerW: 0.1,
    powerDisplay: "~100 mW (peak LED)",
  },
  // Walkie-Talkie (FRS / GMRS)
  {
    id: "walkie-talkie",
    name: "Walkie-Talkie",
    fullName: "FRS / GMRS Handheld Radio",
    frequency: 462e6,
    freqDisplay: "462 – 467 MHz",
    color: "#ffaa22",
    svgIcon: "walkietalkie",
    description: "Handheld half-duplex two-way radios on the FRS / GMRS shared channels",
    examples: [
      "Family hiking radios",
      "Ski-resort staff",
      "Warehouse & event crews",
      "Neighborhood watch",
    ],
    band: "UHF",
    range: "~2 – 8 km (line-of-sight)",
    standard: "FCC Part 95 (FRS / GMRS)",
    powerW: 2,
    powerDisplay: "0.5 – 5 W",
  },
  // Bluetooth
  {
    id: "bluetooth",
    name: "Bluetooth",
    fullName: "Bluetooth Wireless Technology",
    frequency: 2.4e9,
    freqDisplay: "2.4 – 2.485 GHz",
    color: "#0082fc",
    svgIcon: "bluetooth",
    description: "Short-range wireless protocol for personal area networks",
    examples: [
      "Wireless headphones (AirPods)",
      "Keyboards & mice",
      "Fitness trackers",
      "Car audio systems",
    ],
    band: "UHF",
    range: "~10–100 m",
    standard: "IEEE 802.15.1",
    powerW: 0.01,
    powerDisplay: "1 – 100 mW (Class 1–3)",
  },
  // Wi-Fi 2.4 GHz
  {
    id: "wifi-24",
    name: "Wi-Fi 2.4 GHz",
    fullName: "Wi-Fi 802.11b/g/n (2.4 GHz)",
    frequency: 2.45e9,
    freqDisplay: "2.4 – 2.5 GHz",
    color: "#00aaff",
    svgIcon: "wifi",
    description: "Most common Wi-Fi band with longer range and better wall penetration",
    examples: [
      "Home routers (802.11n)",
      "Smart home devices (IoT)",
      "Older laptops & phones",
      "Wi-Fi cameras",
    ],
    band: "UHF",
    range: "~50 m indoors",
    standard: "IEEE 802.11b/g/n",
    powerW: 0.1,
    powerDisplay: "20 – 100 mW",
  },
  // Wi-Fi 5 GHz
  {
    id: "wifi-5",
    name: "Wi-Fi 5 GHz",
    fullName: "Wi-Fi 802.11a/n/ac (5 GHz)",
    frequency: 5.5e9,
    freqDisplay: "5.1 – 5.9 GHz",
    color: "#0066ff",
    svgIcon: "wifi",
    description: "Faster Wi-Fi band with less interference, shorter range",
    examples: [
      "Modern home routers (802.11ac)",
      "Wi-Fi 5 / Wi-Fi 6 devices",
      "Video streaming",
      "Gaming consoles",
    ],
    band: "SHF",
    range: "~30 m indoors",
    standard: "IEEE 802.11a/n/ac/ax",
    powerW: 0.2,
    powerDisplay: "50 – 200 mW",
  },
  // Ultra-Wideband (Apple U1 / U2)
  {
    id: "uwb",
    name: "UWB (Apple U1)",
    fullName: "Ultra-Wideband (Apple U1 / U2)",
    frequency: 6.5e9,
    freqDisplay: "6.24 – 8.24 GHz",
    color: "#22ddff",
    svgIcon: "uwb",
    description: "Wide-spectrum radio pulses giving centimeter-level indoor positioning",
    examples: [
      "AirTag Precision Finding",
      "iPhone hand-off to HomePod",
      "BMW / Genesis digital car keys",
      "Nearby Interaction between iPhones",
    ],
    band: "SHF",
    range: "~10 – 30 m",
    standard: "IEEE 802.15.4z",
    powerW: 0.0005,
    powerDisplay: "< 1 mW (spectral density limit)",
  },
  // Microwave Oven
  {
    id: "microwave",
    name: "Microwave Oven",
    fullName: "Consumer Microwave Oven",
    frequency: 2.45e9,
    freqDisplay: "2.45 GHz",
    color: "#ff4400",
    svgIcon: "microwave",
    description: "Uses microwave radiation to heat food by exciting water molecules",
    examples: [
      "Consumer countertop ovens",
      "Commercial kitchen ovens",
      "Reheating food & beverages",
      "Defrosting frozen foods",
    ],
    band: "UHF/SHF",
    range: "Contained within oven",
    standard: "ISM 2.45 GHz band",
    powerW: 1000,
    powerDisplay: "700 W – 1.2 kW",
  },
  // Cellular 4G LTE
  {
    id: "4g-lte",
    name: "4G LTE",
    fullName: "4G Long-Term Evolution",
    frequency: 1.8e9,
    freqDisplay: "700 MHz – 2.6 GHz",
    color: "#ff6600",
    svgIcon: "cellular",
    description: "Fourth-generation cellular standard enabling mobile broadband",
    examples: [
      "Smartphone internet (AT&T, Verizon)",
      "Mobile hotspots",
      "LTE-M IoT devices",
      "Tablet data connections",
    ],
    band: "UHF",
    range: "~10 km per tower",
    standard: "3GPP Release 8+",
    powerW: 0.25,
    powerDisplay: "250 mW (phone) / 40 W (tower)",
  },
  // Cellular 5G
  {
    id: "5g",
    name: "5G",
    fullName: "Fifth Generation Cellular",
    frequency: 28e9,
    freqDisplay: "600 MHz – 100 GHz",
    color: "#ff3300",
    svgIcon: "cellular",
    description: "Next-gen cellular for ultra-fast speeds and massive device density",
    examples: [
      "5G smartphones (iPhone 15, Galaxy S24)",
      "Fixed wireless home internet",
      "Smart city infrastructure",
      "Autonomous vehicle communication",
    ],
    band: "SHF (mmWave)",
    range: "~100 m (mmWave)",
    standard: "3GPP Release 15+",
    powerW: 0.2,
    powerDisplay: "200 mW (phone) / 50 W (base station)",
  },
  // Satellite (GPS)
  {
    id: "gps",
    name: "GPS Satellite",
    fullName: "Global Positioning System",
    frequency: 1.575e9,
    freqDisplay: "1.575 GHz (L1)",
    color: "#ffcc00",
    svgIcon: "satellite",
    description: "Satellite navigation constellation for global positioning",
    examples: [
      "Smartphone GPS (Google Maps)",
      "Aviation navigation",
      "Maritime navigation",
      "Precision agriculture",
    ],
    band: "UHF",
    range: "Global (20,200 km altitude)",
    standard: "ICD-GPS-200",
    powerW: 50,
    powerDisplay: "~50 W (satellite transmit)",
  },
  // Satellite (Starlink / Ka-band)
  {
    id: "satellite-internet",
    name: "Satellite Internet",
    fullName: "Broadband Satellite (Ka-band)",
    frequency: 20e9,
    freqDisplay: "17.7 – 30 GHz (Ka-band)",
    color: "#ffaa00",
    svgIcon: "satellite",
    description: "High-throughput satellite broadband internet",
    examples: [
      "Starlink (SpaceX LEO)",
      "HughesNet / ViaSat (GEO)",
      "OneWeb broadband",
      "In-flight Wi-Fi (ViaSat)",
    ],
    band: "SHF",
    range: "Global coverage",
    standard: "Ka-band ITU allocation",
    powerW: 25,
    powerDisplay: "~25 W (user terminal uplink)",
  },
  // Automotive Millimeter-Wave Radar (EHF)
  {
    id: "auto-radar",
    name: "Auto Radar",
    fullName: "Automotive Millimeter-Wave Radar",
    frequency: 77e9,
    freqDisplay: "76 – 81 GHz",
    color: "#33ffaa",
    svgIcon: "radar",
    description: "Millimeter-wave radar on cars for cruise control and collision avoidance",
    examples: [
      "Adaptive cruise control",
      "Automatic emergency braking",
      "Blind-spot monitoring",
      "Forward-collision radar (Tesla, Waymo)",
    ],
    band: "EHF",
    range: "~150 – 250 m",
    standard: "ETSI EN 302 264 (77 GHz)",
    powerW: 0.05,
    powerDisplay: "10 – 100 mW",
  },
  // Apple TrueDepth Camera (Near-IR)
  {
    id: "truedepth",
    name: "TrueDepth",
    fullName: "Apple TrueDepth Camera (Face ID)",
    frequency: 319e12, // ~940 nm VCSEL
    freqDisplay: "~319 THz (940 nm)",
    color: "#ff5566",
    svgIcon: "truedepth",
    description: "Projects ~30,000 near-infrared dots to build a 3-D depth map of a face",
    examples: [
      "Face ID authentication (iPhone / iPad Pro)",
      "Animoji & Memoji facial tracking",
      "Portrait-mode selfie lighting",
      "AR face effects",
    ],
    band: "Near-IR",
    range: "~20 – 50 cm",
    standard: "Apple TrueDepth (940 nm)",
    powerW: 0.03,
    powerDisplay: "~30 mW (VCSEL array)",
  },
  // Fiber Optic
  {
    id: "fiber",
    name: "Fiber Optic",
    fullName: "Optical Fiber Communication",
    frequency: 193e12,
    freqDisplay: "~193 THz (1550 nm)",
    color: "#00ffaa",
    svgIcon: "fiber",
    description: "Transmits data as pulses of light through glass fiber strands",
    examples: [
      "Home broadband (FTTH/GPON)",
      "Internet backbone infrastructure",
      "Submarine ocean cables",
      "Data center interconnects",
    ],
    band: "IR/Near-IR",
    range: "Hundreds of km (with repeaters)",
    standard: "ITU-T G.652 / G.657",
    powerW: 0.005,
    powerDisplay: "~5 mW (laser transmitter)",
  },
  // RFID
  {
    id: "rfid",
    name: "RFID",
    fullName: "Radio Frequency Identification",
    frequency: 915e6,
    freqDisplay: "125 kHz – 960 MHz",
    color: "#cc44ff",
    svgIcon: "rfid",
    description: "Uses radio waves to read and capture data from tags",
    examples: [
      "Retail inventory tracking",
      "Library book management",
      "Livestock tracking",
      "Passport chips (e-passports)",
    ],
    band: "UHF",
    range: "Up to 12 m (UHF)",
    standard: "ISO 18000 / EPCglobal",
    powerW: 1,
    powerDisplay: "0.1 – 2 W (reader EIRP)",
  },
  // Radar
  {
    id: "radar",
    name: "Radar",
    fullName: "Radio Detection and Ranging",
    frequency: 10e9,
    freqDisplay: "1 – 100 GHz",
    color: "#00ff88",
    svgIcon: "radar",
    description: "Detects objects by transmitting radio waves and sensing reflections",
    examples: [
      "Air traffic control (ATC)",
      "Weather Doppler radar",
      "Automotive collision warning",
      "Police speed guns",
    ],
    band: "SHF",
    range: "Up to 400 km (military)",
    standard: "Various IEEE radar bands",
    powerW: 50000,
    powerDisplay: "50 mW – 1 MW (varies by system)",
  },
  // Visible-Light LED
  {
    id: "led-light",
    name: "LED Light",
    fullName: "Visible-Light LED",
    frequency: 500e12,
    freqDisplay: "~430 – 750 THz",
    color: "#ffee66",
    svgIcon: "lightbulb",
    description: "Solid-state emitters producing visible light for illumination and displays",
    examples: [
      "Home & office lighting",
      "TV & phone display backlights",
      "Car headlights",
      "Traffic signals",
    ],
    band: "Visible",
    range: "Optical line-of-sight",
    standard: "IEC 62504",
    powerW: 15,
    powerDisplay: "3 – 100 W (bulb)",
  },
  // UV-C Germicidal Light
  {
    id: "uv-sterilizer",
    name: "UV-C Sterilizer",
    fullName: "Ultraviolet-C Germicidal Light",
    frequency: 1.18e15, // ~254 nm
    freqDisplay: "~1.18 PHz (254 nm)",
    color: "#aa55ff",
    svgIcon: "uv",
    description: "Short-wavelength UV that damages microbial DNA to disinfect surfaces and water",
    examples: [
      "Hospital-room disinfection lamps",
      "Municipal drinking-water treatment",
      "HVAC in-duct sterilizers",
      "Phone / toothbrush UV cases",
    ],
    band: "UV-C",
    range: "Direct exposure (cm – m)",
    standard: "IEC 62471 (photobiological safety)",
    powerW: 30,
    powerDisplay: "10 – 100 W",
  },
  // Diagnostic Medical X-Ray
  {
    id: "xray-medical",
    name: "Medical X-Ray",
    fullName: "Diagnostic Medical X-Ray",
    frequency: 3e18, // ~12 keV
    freqDisplay: "~3 × 10¹⁸ Hz (~12 keV)",
    color: "#bb00ff",
    svgIcon: "xray",
    description: "Ionizing radiation that penetrates soft tissue to image bone and internal structures",
    examples: [
      "Dental & chest X-rays",
      "CT scans",
      "Airport carry-on scanners",
      "Mammography",
    ],
    band: "X-Ray",
    range: "Contained in shielded rooms",
    standard: "IEC 60601-2-54",
    powerW: 2500,
    powerDisplay: "~2.5 kW (tube during exposure)",
  },
  // PET / Gamma Imaging
  {
    id: "gamma-pet",
    name: "PET / Gamma",
    fullName: "PET Scan Gamma Imaging",
    frequency: 1.24e20, // 511 keV annihilation photons
    freqDisplay: "~1.24 × 10²⁰ Hz (511 keV)",
    color: "#ff44ff",
    svgIcon: "gamma",
    description: "Detects gamma photons emitted by positron annihilation in radiotracers",
    examples: [
      "Oncology PET-CT scans",
      "Brain metabolism imaging",
      "Cardiac perfusion studies",
      "Radiopharmaceutical uptake mapping",
    ],
    band: "Gamma",
    range: "Detector ring (~50 cm)",
    standard: "IEC 61675-1 (PET performance)",
    powerW: 0.00006,
    powerDisplay: "~60 μW (10 mCi radiotracer)",
  },
];

// Format frequency for display
export function formatFrequency(hz) {
  if (hz >= 1e18) return `${(hz / 1e18).toPrecision(3)} EHz`;
  if (hz >= 1e15) return `${(hz / 1e15).toPrecision(3)} PHz`;
  if (hz >= 1e12) return `${(hz / 1e12).toPrecision(3)} THz`;
  if (hz >= 1e9) return `${(hz / 1e9).toPrecision(3)} GHz`;
  if (hz >= 1e6) return `${(hz / 1e6).toPrecision(3)} MHz`;
  if (hz >= 1e3) return `${(hz / 1e3).toPrecision(3)} kHz`;
  return `${hz.toPrecision(3)} Hz`;
}

// Convert Hz to log10 position (0–1 scale from 3 Hz to 3e22 Hz)
const LOG_MIN = Math.log10(3);
const LOG_MAX = Math.log10(3e22);

export function freqToPosition(hz) {
  const logVal = Math.log10(hz);
  return (logVal - LOG_MIN) / (LOG_MAX - LOG_MIN);
}

export { LOG_MIN, LOG_MAX };
